spring:
  application:
    name: employee-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:usersdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    defer-datasource-initialization: false
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true

flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: true

# ===============================
# Custom properties
# ===============================
user:
  password:
    regex: "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z]).{8,}$"
  email:
    regex: '^([_A-Za-z0-9-+]+\.?[_A-Za-z0-9-+]+@(smartjob.cl))$'

security:
  excluded-urls: /smartjob/api/v1/users, /smartjob/api/v1/login, /h2-console/login.do